name: dns-docker
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - brotli=1.0.9=he6710b0_2
  - ca-certificates=2023.01.10=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.0=py38hd667e15_1
  - cryptography=37.0.1=py38h9ce1e76_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - dnslib=0.9.19=pyhd8ed1ab_0
  - dnspython=2.2.1=py38h06a4308_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.4.4=h295c915_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipython=8.4.0=py38h06a4308_0
  - jedi=0.18.1=py38h06a4308_1
  - jpeg=9e=h7f8727e_0
  - kiwisolver=1.4.2=py38h295c915_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=h2818925_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.15=h7f8727e_0
  - libxml2=2.9.14=h74e7548_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib=3.5.1=py38h06a4308_1
  - matplotlib-base=3.5.1=py38ha18d171_1
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - munkres=1.1.4=py_0
  - ncurses=6.3=h7f8727e_2
  - numpy=1.22.3=py38he7a7128_0
  - numpy-base=1.22.3=py38hf524024_0
  - openssl=1.1.1t=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.5.3=py38h417a72b_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=9.2.0=py38hace64e9_0
  - pip=21.2.4=py38h06a4308_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyparsing=3.0.4=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - python=3.8.13=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - qt=5.9.7=h5867ecd_1
  - readline=8.1.2=h7f8727e_1
  - scapy=2.4.3=py_0
  - scikit-learn=1.3.0=py38h1128e8f_1
  - setuptools=61.2.0=py38h06a4308_0
  - sip=4.19.13=py38h295c915_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.38.5=hc218d9a_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tk=8.6.12=h1ccaba5_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.2=ha4553b6_0
  - pip:
      - attrs==22.1.0
      - beautifulsoup4==4.11.1
      - charset-normalizer==2.1.0
      - cloudflare==2.10.2
      - docker==6.0.1
      - idna==3.3
      - jsonlines==3.1.0
      - pyyaml==6.0
      - requests==2.28.1
      - soupsieve==2.3.2.post1
      - urllib3==1.26.9
      - websocket-client==1.3.3
prefix: /home/qifanz/.conda/envs/dns-docker
